{
  "wow": ["za"],
  "errorPhrases": {
    "keys": {
      "200019": {
        "en": "this is error phrase in english",
        "th": "นี่คือเออเร่อภาษาไทย"
      },
      "200020": {
        "en": "wow another error",
        "th": "นี่มันอีก error นี่นา"
      },
      "200021": {
        "en": "asdf",
        "th": "ฟหกด"
      }
    }
  }
}
